// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQTQ1l2SzIFQku3c43cNyY1DlRKkJo8Y',
    appId: '1:541048024492:android:2996dc433b936e0f93de09',
    messagingSenderId: '541048024492',
    projectId: 'diamond-pos-dev',
    databaseURL: 'https://diamond-pos-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diamond-pos-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIv0DeW4f9IjviASsTuuh5Jqld4IE1QQ',
    appId: '1:541048024492:ios:ca3c6eb3ddfa3e4f93de09',
    messagingSenderId: '541048024492',
    projectId: 'diamond-pos-dev',
    databaseURL: 'https://diamond-pos-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diamond-pos-dev.appspot.com',
    iosClientId: '541048024492-1ce53l35i0nc4o5alqafun6ihgmhmb1c.apps.googleusercontent.com',
    iosBundleId: 'com.IG.diamondapp.diamondApp',
  );
}
